export const productsDummy = [
  {
    category_id: 1,
    category_name_en: null,
    category_name_ar: "منتج جاهز",
    details_en: null,
    details_ar: "المنتجات الملموسه والقابله للشحن",
    created_at: "2024-12-12T14:52:26.346",
    updated_at: "2025-01-16T05:43:55.1400574",
    brandsDto: [
      {
        brand_id: 1,
        brand_name: "shoes",
        details: "عامه",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        productDto: [
          {
            product_id: 1,
            product_name_en: null,
            product_name_ar: "shoes01",
            price: 150,
            photoes: [
              "linda-xu-fUEP0djb1hA-unsplash.jpg",
              "malvestida-DMl5gG0yWWY-unsplash.jpg",
            ],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T05:48:32.320989",
            updated_at: "2025-01-16T05:48:32.3210306",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 1,
                cost_price: 0.0,
                price: 0.0,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 1,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 1,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [
              {
                product_colors_id: 1,
                color_name: "red",
                price: 0.0,
                hex_code: "red",
                created_at: "2025-01-16T05:48:32.6768713",
                updated_at: "2025-01-16T05:48:32.6772815",
                photoes: [
                  "linda-xu-fUEP0djb1hA-unsplash.jpg",
                  "malvestida-DMl5gG0yWWY-unsplash.jpg",
                ],
                size: ["41", "42", "43", "44", "45"],
                size_price: ["50", "60", "70", "80", "90"],
                cost: ["120", "130", "140", "150", "160"],
                quantity: ["5", "6", "7", "8", "9"],
              },
            ],
            attached_filesDto: [
              {
                attached_files_id: 1,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 1,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 1,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 1,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: null,
          },
          {
            product_id: 2,
            product_name_en: null,
            product_name_ar: "shoes02",
            price: 120,
            photoes: ["paul-volkmer-updW-QUccFE-unsplash.jpg"],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T16:37:16.8764528",
            updated_at: "2025-01-16T16:37:16.8765126",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 2,
                cost_price: 0.0,
                price: 0.0,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 2,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 2,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [
              {
                product_colors_id: 2,
                color_name: "red",
                price: 0.0,
                hex_code: "red",
                created_at: "2025-01-16T05:48:32.6768713",
                updated_at: "2025-01-16T05:48:32.6772815",
                photoes: [
                  "mehdi-thomas-boutdarine-OVUrzAAMTdg-unsplash.jpg",
                  "malvestida-DMl5gG0yWWY-unsplash.jpg",
                ],
                size: ["41", "42", "43"],
                size_price: ["50", "60", "70"],
                cost: ["120", "130", "140"],
                quantity: ["5", "6", "7"],
              },
              {
                product_colors_id: 3,
                color_name: "red",
                price: 0.0,
                hex_code: "red",
                created_at: "2025-01-16T05:48:32.6768713",
                updated_at: "2025-01-16T05:48:32.6772815",
                photoes: [
                  "linda-xu-fUEP0djb1hA-unsplash.jpg",
                  "pexels-craytive-1464625.jpg",
                ],
                size: ["41", "42", "43", "44", "45"],
                size_price: ["50", , "90"],
                cost: ["120", "160"],
                quantity: ["5", "9"],
              },
              ,
            ],
            attached_filesDto: [
              {
                attached_files_id: 2,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 2,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 2,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 2,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: null,
          },
        ],
        trade_marksDto: [
          {
            trade_mark_id: 1,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
          {
            trade_mark_id: 2,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
        ],
      },
    ],
  },
  {
    category_id: 2,
    category_name_en: null,
    category_name_ar: "خدمه حسب الطلب",
    details_en: null,
    details_ar: "التصميم,الطباعه",
    created_at: "2025-01-16T05:44:42.3213401",
    updated_at: "2025-01-16T05:44:42.3213492",
    brandsDto: [],
  },
  {
    category_id: 3,
    category_name_en: null,
    category_name_ar: "اكل",
    details_en: null,
    details_ar: "الماكولات والمشروبات",
    created_at: "2025-01-16T05:45:07.6150025",
    updated_at: "2025-01-16T05:45:07.6150326",
    brandsDto: [
      {
        brand_id: 2,
        brand_name: "food",
        details: "عامه",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        productDto: [
          {
            product_id: 5,
            product_name_en: null,
            product_name_ar: "cake",
            price: 150,
            photoes: ["food1.jpg", "food2.jpg"],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T05:48:32.320989",
            updated_at: "2025-01-16T05:48:32.3210306",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 1,
                cost_price: 0.0,
                price: 60,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 1,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 1,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [],
            attached_filesDto: [
              {
                attached_files_id: 1,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 1,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 1,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 1,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: null,
          },
          {
            product_id: 9,
            product_name_en: null,
            product_name_ar: "salad",
            price: 150,
            photoes: ["food2.jpg"],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T05:48:32.320989",
            updated_at: "2025-01-16T05:48:32.3210306",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 1,
                cost_price: 0.0,
                price: 60,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 1,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 1,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [],
            attached_filesDto: [
              {
                attached_files_id: 1,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 1,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 1,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 1,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: null,
          },
          {
            product_id: 6,
            product_name_en: null,
            product_name_ar: "juce",
            price: 120,
            photoes: ["food4.jpg"],
            description_en: null,
            description_ar: "string",
            created_at: "2025-01-16T16:37:16.8764528",
            updated_at: "2025-01-16T16:37:16.8765126",
            rating_number: 0,
            productDetailDto: [
              {
                product_details_id: 2,
                cost_price: 0.0,
                price: 0.0,
                price_after_discount: 0.0,
                end_discount_date: "string",
                store_code: "string",
                gtin: "string",
                mpn: "string",
                trade_mark: 2,
                second_address: "string",
                ads_address: "string",
                discount: 0,
                percent: 0,
                amount_options: "string",
                product_view_channels: "string",
                file_attach: true,
                write_note: true,
                under_taxes: true,
                details_en: null,
                details_ar: "string",
                weight: 0,
                tags: "string",
                is_featured: true,
                rate: 0,
                rate_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            alertsDto: [
              {
                alert_id: 2,
                amount: 0,
                amount_of_clients: 0,
                percentt: 0,
                created_at: null,
                updated_at: null,
              },
            ],
            product_colors: [],
            attached_filesDto: [
              {
                attached_files_id: 2,
                attached_file_name: "string",
                attached_file_details: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            seo_detailsDto: [
              {
                seo_details_id: 2,
                page_title: "string",
                seo_page_url: "string",
                page_description: "string",
                netflix_link: "string",
                created_at: null,
                updated_at: null,
              },
            ],
            product_statusDto: [
              {
                product_status_id: 2,
                product_status_en: null,
                product_status_ar: "string",
                product_status_details_ar: "string",
                product_status_details_en: null,
                created_at: null,
                updated_at: null,
              },
            ],
            moreDto: [
              {
                more_id: 2,
                more_en: null,
                more_ar: "string",
                more_details_ar: "string",
                more_details_en: null,
              },
            ],
            trade_marksDto: [
              {
                trade_mark_id: 1,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
              {
                trade_mark_id: 2,
                trade_mark_name_en: null,
                trade_mark_name_ar: "علامة تجارية جديدة",
                trade_mark_details_en: null,
                trade_mark_details_ar:
                  "تفاصيل العلامة التجارية الجديدة باللغة العربية",
              },
            ],
            ratingDto: null,
          },
        ],
        trade_marksDto: [
          {
            trade_mark_id: 1,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
          {
            trade_mark_id: 2,
            trade_mark_name_en: null,
            trade_mark_name_ar: "علامة تجارية جديدة",
            trade_mark_details_en: null,
            trade_mark_details_ar:
              "تفاصيل العلامة التجارية الجديدة باللغة العربية",
          },
        ],
      },
    ],
  },

  {
    category_id: 5,
    category_name_en: null,
    category_name_ar: "بطاقه رقميه",
    details_en: null,
    details_ar: "بطاقات شحن",
    created_at: "2025-01-16T05:46:07.5039791",
    updated_at: "2025-01-16T05:46:07.5039865",
    brandsDto: [],
  },
];

export const allCategories = [
  {
    category_id: 1,
    category_name_en: null,
    category_name_ar: "منتج جديد",
    details_en: null,
    details_ar: "منتج جديد",
    created_at: "2025-03-08T04:53:21.6935798",
    updated_at: "2025-03-08T04:53:21.6936525",
    brandsdto: [
      {
        brand_id: 1,
        brand_name: "عامه",
        details: "عامه",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 1,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
      {
        brand_id: 2,
        brand_name: "عبايات",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 2,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
          {
            trade_mark_id: 3,
            trade_mark_name_en: "علامه تجاريه1",
            trade_mark_name_ar: "علامه تجاريه1",
            trade_mark_details_en: "",
            trade_mark_details_ar: "علامه تجاريه1",
          },
        ],
      },
      {
        brand_id: 4,
        brand_name: "new",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 5,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
      {
        brand_id: 5,
        brand_name: "new1",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 6,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
      {
        brand_id: 6,
        brand_name: "tesa",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 7,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
      {
        brand_id: 7,
        brand_name: "tesa",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 8,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
      {
        brand_id: 8,
        brand_name: "tesa",
        details: "Nike is a leading brand in sportswear and equip",
        add_to_main_brand: true,
        created_at: null,
        updated_at: null,
        trade_marksdto: [
          {
            trade_mark_id: 9,
            trade_mark_name_en: "general",
            trade_mark_name_ar: "عامه",
            trade_mark_details_en: "general",
            trade_mark_details_ar: "عامه",
          },
        ],
      },
    ],
  },
];

export const allbrands = [
  {
    brand_id: 0,
    brand_name: "string",
    details: "string",
    add_to_main_brand: true,
    photo: "string",
    created_at: "2025-04-18T07:08:18.086Z",
    updated_at: "2025-04-18T07:08:18.086Z",
    category_id: 0,
    categories: {
      category_id: 0,
      category_name_en: "string",
      category_name_ar: "string",
      details_en: "string",
      details_ar: "string",
      category_photo: "string",
      created_at: "2025-04-18T07:08:18.086Z",
      updated_at: "2025-04-18T07:08:18.086Z",
      brands: ["string"],
      userId: 0,
      users: {
        userId: 0,
        name: "string",
        mobile: "string",
        email: "string",
        otp: "string",
        password: "string",
        userPhoto: "string",
        role: "string",
        active: true,
        photo: "string",
        firstorder: true,
        is_client: true,
        passhash: "string",
        passhashsalt: "string",
        aspNetUserRoles: [
          {
            id: 0,
            role_Name: "string",
            userId: 0,
            users: "string",
          },
        ],
        categories: ["string"],
        productsFavourite: [
          {
            products_favourite_id: 0,
            user_id: 0,
            users: "string",
            product_id: 0,
            products: "string",
          },
        ],
        shopping_cart: [
          {
            shopping_cart_id: 0,
            product_name: "string",
            price: 0,
            quantity: 0,
            total_amount: 0,
            status: "string",
            created_at: "2025-04-18T07:08:18.086Z",
            updated_at: "2025-04-18T07:08:18.086Z",
            product_id: 0,
            products: {
              product_id: 0,
              product_name_en: "string",
              product_name_ar: "string",
              price: 0,
              photoes: ["string"],
              description_en: "string",
              description_ar: "string",
              created_at: "2025-04-18T07:08:18.086Z",
              updated_at: "2025-04-18T07:08:18.086Z",
              rating_number: 0,
              product_details: [
                {
                  product_details_id: 0,
                  cost_price: 0,
                  price: 0,
                  price_after_discount: 0,
                  end_discount_date: "string",
                  store_code: "string",
                  gtin: "string",
                  mpn: "string",
                  trade_mark: "string",
                  second_address: "string",
                  ads_address: "string",
                  discount: 0,
                  percent: 0,
                  amount_options: "string",
                  product_view_channels: "string",
                  file_attach: true,
                  write_note: true,
                  under_taxes: true,
                  details_en: "string",
                  details_ar: "string",
                  weight: 0,
                  tags: "string",
                  is_featured: true,
                  rate: 0,
                  rate_details: "string",
                  created_at: "2025-04-18T07:08:18.086Z",
                  updated_at: "2025-04-18T07:08:18.086Z",
                  product_id: 0,
                  products: "string",
                },
              ],
              alerts: [
                {
                  alert_id: 0,
                  amount: 0,
                  amount_of_clients: 0,
                  percentt: 0,
                  created_at: "2025-04-18T07:08:18.086Z",
                  updated_at: "2025-04-18T07:08:18.086Z",
                  product_id: 0,
                  products: "string",
                },
              ],
              attached_files: [
                {
                  attached_files_id: 0,
                  attached_file_name: "string",
                  attached_file_details: "string",
                  created_at: "2025-04-18T07:08:18.086Z",
                  updated_at: "2025-04-18T07:08:18.086Z",
                  product_id: 0,
                  products: "string",
                },
              ],
              product_colors: [
                {
                  product_colors_id: 0,
                  color_name: "string",
                  price: 0,
                  hex_code: "string",
                  size: ["string"],
                  size_Price: ["string"],
                  cost: ["string"],
                  quantity: ["string"],
                  photoes: ["string"],
                  created_at: "2025-04-18T07:08:18.087Z",
                  updated_at: "2025-04-18T07:08:18.087Z",
                  product_id: 0,
                  products: "string",
                },
              ],
              seo_details: [
                {
                  seo_details_id: 0,
                  page_title: "string",
                  seo_page_url: "string",
                  page_description: "string",
                  netflix_link: "string",
                  created_at: "2025-04-18T07:08:18.087Z",
                  updated_at: "2025-04-18T07:08:18.087Z",
                  product_id: 0,
                  products: "string",
                },
              ],
              product_status: [
                {
                  product_status_id: 0,
                  product_status_en: "string",
                  product_status_ar: "string",
                  product_status_details_ar: "string",
                  product_status_details_en: "string",
                  product_id: 0,
                  products: "string",
                },
              ],
              products_favourite: [
                {
                  products_favourite_id: 0,
                  user_id: 0,
                  users: "string",
                  product_id: 0,
                  products: "string",
                },
              ],
              rating: [
                {
                  rating_id: 0,
                  rating_number: 0,
                  rating_comment: "string",
                  created_at: "2025-04-18T07:08:18.087Z",
                  updated_at: "2025-04-18T07:08:18.087Z",
                  product_messages: [
                    {
                      product_messages_id: 0,
                      from: "string",
                      to: "string",
                      messages: "string",
                      is_visible: true,
                      created_at: "2025-04-18T07:08:18.087Z",
                      updated_at: "2025-04-18T07:08:18.087Z",
                      rating_id: 0,
                      rating: "string",
                    },
                  ],
                  product_id: 0,
                  products: "string",
                  userId: 0,
                  users: "string",
                },
              ],
              more: [
                {
                  more_id: 0,
                  more_en: "string",
                  more_ar: "string",
                  more_details_ar: "string",
                  more_details_en: "string",
                  product_id: 0,
                  products: "string",
                },
              ],
              brand_id: 0,
              brands: "string",
              trade_mark_id: 0,
              trade_marks: {
                trade_mark_id: 0,
                trade_mark_name_en: "string",
                trade_mark_name_ar: "string",
                trade_mark_details_en: "string",
                trade_mark_details_ar: "string",
                products: ["string"],
                brand_id: 0,
                brands: "string",
              },
            },
            userId: 0,
            users: "string",
            order_id: 0,
            orders: {
              order_id: 0,
              status: "string",
              admin_id: 0,
              user_id: 0,
              total_amount: 0,
              payment_id: 0,
              created_at: "2025-04-18T07:08:18.087Z",
              updated_at: "2025-04-18T07:08:18.087Z",
              shopping_cart: ["string"],
              notifications: ["string"],
            },
          },
        ],
        rating: [
          {
            rating_id: 0,
            rating_number: 0,
            rating_comment: "string",
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_messages: [
              {
                product_messages_id: 0,
                from: "string",
                to: "string",
                messages: "string",
                is_visible: true,
                created_at: "2025-04-18T07:08:18.087Z",
                updated_at: "2025-04-18T07:08:18.087Z",
                rating_id: 0,
                rating: "string",
              },
            ],
            product_id: 0,
            products: "string",
            userId: 0,
            users: "string",
          },
        ],
        notifications: [
          {
            notifications_id: 0,
            status: "string",
            createdat: "2025-04-18T07:08:18.087Z",
            userId: 0,
            users: "string",
            order_id: 0,
            orders: {
              order_id: 0,
              status: "string",
              admin_id: 0,
              user_id: 0,
              total_amount: 0,
              payment_id: 0,
              created_at: "2025-04-18T07:08:18.087Z",
              updated_at: "2025-04-18T07:08:18.087Z",
              shopping_cart: ["string"],
              notifications: ["string"],
            },
          },
        ],
        dynamic_photoes: [
          {
            dynamic_photoes_id: 0,
            redirecting_banners_method: "string",
            expanding_banner: true,
            routing_banners: true,
            automaticlly_moving_banners: true,
            disappearing_below_banners: true,
            disappearing_shares: true,
            tab_id: 0,
            item_background_color: "string",
            background_item_photo: "string",
            mobile_item_view_only: true,
            computer_and_tablet_item_view_only: true,
            item_view_in_interface_with_arabic_only: true,
            item_view_in_interface_with_english_only: true,
            angel_animation: "string",
            classes: "string",
            arrange: 0,
            dynamic_photoes_banners: [
              {
                dynamic_photoes_banners_id: 0,
                video_or_photo_link: "string",
                main_banner_photo: "string",
                mobile_banner_photo: "string",
                without_background_photo: "string",
                adding_transparent_black_background: true,
                main_text: "string",
                main_text_animation: "string",
                main_text_color: "string",
                additional_text: "string",
                additional_text_animation: "string",
                additional_text_color: "string",
                reverse_texts_direction: true,
                texts_in_middle: true,
                discount_activation_in_banner: true,
                end_discount_date: "string",
                banner_or_button_link: "string",
                banner_or_button_type: "string",
                sign: "string",
                banner_or_button_name: "string",
                button_animation: "string",
                disappearing_button: true,
                button_without_background_color: true,
                button_with_circle_edges: true,
                reverse_button_with_text: true,
                dynamic_photoes_id: 0,
                dynamic_photoes: "string",
              },
            ],
            userId: 0,
            users: "string",
          },
        ],
        squared_photoes: [
          {
            squared_photoes_id: 0,
            main_section_title: "string",
            sub_section_title: "string",
            network_view_instead_of_slider: true,
            number_of_culomns_in_computer_and_tablet: "string",
            number_of_culomns_in_mobile: "string",
            free_state_to_photoes_slider: true,
            photoes_routing: true,
            automatic_moving_for_photoes: true,
            appearing_part_of_latest_photoes: true,
            disappearing_shares: true,
            photoes_edges_shap: "string",
            text_in_middle_of_photoes: true,
            viewing_texts_over_photoes: true,
            tab_id_for_main_page_en: "string",
            item_background_color: true,
            background_photo: "string",
            viewing_item_in_mobile_only: true,
            viewing_item_in_computer_and_tablet_only: true,
            viewing_item_in_interface_in_arabic_only: true,
            viewing_item_in_interface_in_english_only: true,
            angel_animation: "string",
            classes: "string",
            arrange: 0,
            squared_photoes_banners: [
              {
                squared_photoes_banners_id: 0,
                banner_photo_type: "string",
                banner_photo_link: "string",
                main_text: "string",
                sub_text: "string",
                viewing_sub_text_as_abutton: true,
                link_photo_with_malak: true,
                malak_window_name: "string",
                custom_classes: "string",
                squared_photoes_id: 0,
                squared_photoes: "string",
              },
            ],
            userId: 0,
            users: "string",
          },
        ],
        malak_products: [
          {
            malak_products_id: 0,
            main_part_title: "string",
            sub_part_title: "string",
            title_photo: "string",
            network_view_instead_of_slider: true,
            computer_and_tablet_columns: 0,
            mobile_columns: 0,
            adding_button_and_link: true,
            button_text: "string",
            button_link: "string",
            button_link_type: "string",
            title_in_middle: true,
            appearing_part_of_last_product: true,
            products_in_middle_in_computer: true,
            products_type: "string",
            products_count: "string",
            main_page_tab_id: "string",
            item_background_color: "string",
            item_background_photo: "string",
            item_viewing_in_mobile_only: true,
            item_viewing_in_computer_and_tablet_only: true,
            item_viewing_in_interface_in_arabic: true,
            item_viewing_in_interface_in_english: true,
            angel_animation: "string",
            classes: "string",
            arrange: 0,
            userId: 0,
            users: "string",
          },
        ],
        wide_banner: [
          {
            wide_banner_id: 0,
            banner_photo: "string",
            redirecting_photo_link: "string",
            arrange: 0,
            userId: 0,
            users: "string",
          },
        ],
        malak_trade_marks: [
          {
            malak_trade_marks_id: 0,
            title: "string",
            sub_title: "string",
            main_page_tab_id: 0,
            item_background_color: "string",
            item_background_photo: "string",
            item_viewing_in_mobile_only: true,
            item_viewing_in_computer_and_tablet_only: "string",
            item_viewing_at_interface_in_arabic_only: "string",
            item_viewing_at_interface_in_english_only: "string",
            angel_animation: "string",
            classes: "string",
            arrange: 0,
            userId: 0,
            users: "string",
            trade_mark_id: 0,
            trade_marks: {
              trade_mark_id: 0,
              trade_mark_name_en: "string",
              trade_mark_name_ar: "string",
              trade_mark_details_en: "string",
              trade_mark_details_ar: "string",
              products: ["string"],
              brand_id: 0,
              brands: "string",
            },
          },
        ],
        shop_background: [
          {
            shop_background_id: 0,
            background_photo: "string",
            photo_title: "string",
            link_title: "string",
            redirecting_link: "string",
            transparent_background: true,
            arrange: 0,
            userId: 0,
            users: "string",
          },
        ],
        payment_banner: [
          {
            payment_banner_id: 0,
            redirecting_banners_type: "string",
            banner_fullsize: true,
            routing_banners: true,
            automatic_moving_banners: true,
            invisible_navigation_points_below: true,
            invisible_navigation_shares_in_computer: true,
            main_page_tab_id: 0,
            item_background_color: "string",
            item_background_photo: "string",
            item_viewing_on_mobile_only: true,
            item_viewing_on_computer_and_tablet_only: true,
            item_viewing_at_interface_in_arabic_only: true,
            item_viewing_at_interface_in_english_only: true,
            angel_animation: "string",
            classes: "string",
            arrange: 0,
            payment_banner_details: [
              {
                payment_banner_details_id: 0,
                video_or_photo_link: "string",
                main_banner_photo: "string",
                mobile_banner_photo: "string",
                photo_over_banner: "string",
                transparent_black_background_adding: true,
                main_text: "string",
                main_text_animation: "string",
                main_text_color: "string",
                additional_text: "string",
                additional_text_animation: "string",
                additional_text_color: "string",
                reverse_texts_direction: true,
                texts_in_middle: true,
                discount_activation_in_banner: true,
                discount_end_date: "string",
                button_or_banner_link_type: "string",
                button_or_banner_link: "string",
                sign: "string",
                button_text: "string",
                button_animation: "string",
                invisible_button: true,
                button_wthout_background_color: true,
                button_with_circle_edges: true,
                reverse_button_direction_comparing_with_text: true,
                payment_banner_id: 0,
                payment_banner: "string",
              },
            ],
            userId: 0,
            users: "string",
          },
        ],
        payment_banner_details: [
          {
            payment_banner_details_id: 0,
            video_or_photo_link: "string",
            main_banner_photo: "string",
            mobile_banner_photo: "string",
            photo_over_banner: "string",
            transparent_black_background_adding: true,
            main_text: "string",
            main_text_animation: "string",
            main_text_color: "string",
            additional_text: "string",
            additional_text_animation: "string",
            additional_text_color: "string",
            reverse_texts_direction: true,
            texts_in_middle: true,
            discount_activation_in_banner: true,
            discount_end_date: "string",
            button_or_banner_link_type: "string",
            button_or_banner_link: "string",
            sign: "string",
            button_text: "string",
            button_animation: "string",
            invisible_button: true,
            button_wthout_background_color: true,
            button_with_circle_edges: true,
            reverse_button_direction_comparing_with_text: true,
            payment_banner_id: 0,
            payment_banner: "string",
          },
        ],
      },
    },
    products: [
      {
        product_id: 0,
        product_name_en: "string",
        product_name_ar: "string",
        price: 0,
        photoes: ["string"],
        description_en: "string",
        description_ar: "string",
        created_at: "2025-04-18T07:08:18.087Z",
        updated_at: "2025-04-18T07:08:18.087Z",
        rating_number: 0,
        product_details: [
          {
            product_details_id: 0,
            cost_price: 0,
            price: 0,
            price_after_discount: 0,
            end_discount_date: "string",
            store_code: "string",
            gtin: "string",
            mpn: "string",
            trade_mark: "string",
            second_address: "string",
            ads_address: "string",
            discount: 0,
            percent: 0,
            amount_options: "string",
            product_view_channels: "string",
            file_attach: true,
            write_note: true,
            under_taxes: true,
            details_en: "string",
            details_ar: "string",
            weight: 0,
            tags: "string",
            is_featured: true,
            rate: 0,
            rate_details: "string",
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_id: 0,
            products: "string",
          },
        ],
        alerts: [
          {
            alert_id: 0,
            amount: 0,
            amount_of_clients: 0,
            percentt: 0,
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_id: 0,
            products: "string",
          },
        ],
        attached_files: [
          {
            attached_files_id: 0,
            attached_file_name: "string",
            attached_file_details: "string",
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_id: 0,
            products: "string",
          },
        ],
        product_colors: [
          {
            product_colors_id: 0,
            color_name: "string",
            price: 0,
            hex_code: "string",
            size: ["string"],
            size_Price: ["string"],
            cost: ["string"],
            quantity: ["string"],
            photoes: ["string"],
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_id: 0,
            products: "string",
          },
        ],
        seo_details: [
          {
            seo_details_id: 0,
            page_title: "string",
            seo_page_url: "string",
            page_description: "string",
            netflix_link: "string",
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_id: 0,
            products: "string",
          },
        ],
        product_status: [
          {
            product_status_id: 0,
            product_status_en: "string",
            product_status_ar: "string",
            product_status_details_ar: "string",
            product_status_details_en: "string",
            product_id: 0,
            products: "string",
          },
        ],
        products_favourite: [
          {
            products_favourite_id: 0,
            user_id: 0,
            users: "string",
            product_id: 0,
            products: "string",
          },
        ],
        rating: [
          {
            rating_id: 0,
            rating_number: 0,
            rating_comment: "string",
            created_at: "2025-04-18T07:08:18.087Z",
            updated_at: "2025-04-18T07:08:18.087Z",
            product_messages: [
              {
                product_messages_id: 0,
                from: "string",
                to: "string",
                messages: "string",
                is_visible: true,
                created_at: "2025-04-18T07:08:18.087Z",
                updated_at: "2025-04-18T07:08:18.087Z",
                rating_id: 0,
                rating: "string",
              },
            ],
            product_id: 0,
            products: "string",
            userId: 0,
            users: "string",
          },
        ],
        more: [
          {
            more_id: 0,
            more_en: "string",
            more_ar: "string",
            more_details_ar: "string",
            more_details_en: "string",
            product_id: 0,
            products: "string",
          },
        ],
        brand_id: 0,
        brands: "string",
        trade_mark_id: 0,
        trade_marks: {
          trade_mark_id: 0,
          trade_mark_name_en: "string",
          trade_mark_name_ar: "string",
          trade_mark_details_en: "string",
          trade_mark_details_ar: "string",
          products: ["string"],
          brand_id: 0,
          brands: "string",
        },
      },
    ],
    trade_marks: [
      {
        trade_mark_id: 0,
        trade_mark_name_en: "string",
        trade_mark_name_ar: "string",
        trade_mark_details_en: "string",
        trade_mark_details_ar: "string",
        products: ["string"],
        brand_id: 0,
        brands: "string",
      },
    ],
  },
];

export const alltradmarks = [
  {
    trade_mark_id: 0,
    trade_mark_name_en: "string",
    trade_mark_name_ar: "string",
    trade_mark_details_en: "string",
    trade_mark_details_ar: "string",
    products: [
      {
        product_id: 0,
        product_name_en: "string",
        product_name_ar: "string",
        price: 0,
        photoes: ["string"],
        description_en: "string",
        description_ar: "string",
        created_at: "2025-04-18T07:44:26.517Z",
        updated_at: "2025-04-18T07:44:26.517Z",
        rating_number: 0,
        product_details: [
          {
            product_details_id: 0,
            cost_price: 0,
            price: 0,
            price_after_discount: 0,
            end_discount_date: "string",
            store_code: "string",
            gtin: "string",
            mpn: "string",
            trade_mark: "string",
            second_address: "string",
            ads_address: "string",
            discount: 0,
            percent: 0,
            amount_options: "string",
            product_view_channels: "string",
            file_attach: true,
            write_note: true,
            under_taxes: true,
            details_en: "string",
            details_ar: "string",
            weight: 0,
            tags: "string",
            is_featured: true,
            rate: 0,
            rate_details: "string",
            created_at: "2025-04-18T07:44:26.517Z",
            updated_at: "2025-04-18T07:44:26.517Z",
            product_id: 0,
            products: "string",
          },
        ],
        alerts: [
          {
            alert_id: 0,
            amount: 0,
            amount_of_clients: 0,
            percentt: 0,
            created_at: "2025-04-18T07:44:26.517Z",
            updated_at: "2025-04-18T07:44:26.517Z",
            product_id: 0,
            products: "string",
          },
        ],
        attached_files: [
          {
            attached_files_id: 0,
            attached_file_name: "string",
            attached_file_details: "string",
            created_at: "2025-04-18T07:44:26.517Z",
            updated_at: "2025-04-18T07:44:26.517Z",
            product_id: 0,
            products: "string",
          },
        ],
        product_colors: [
          {
            product_colors_id: 0,
            color_name: "string",
            price: 0,
            hex_code: "string",
            size: ["string"],
            size_Price: ["string"],
            cost: ["string"],
            quantity: ["string"],
            photoes: ["string"],
            created_at: "2025-04-18T07:44:26.517Z",
            updated_at: "2025-04-18T07:44:26.517Z",
            product_id: 0,
            products: "string",
          },
        ],
        seo_details: [
          {
            seo_details_id: 0,
            page_title: "string",
            seo_page_url: "string",
            page_description: "string",
            netflix_link: "string",
            created_at: "2025-04-18T07:44:26.517Z",
            updated_at: "2025-04-18T07:44:26.517Z",
            product_id: 0,
            products: "string",
          },
        ],
        product_status: [
          {
            product_status_id: 0,
            product_status_en: "string",
            product_status_ar: "string",
            product_status_details_ar: "string",
            product_status_details_en: "string",
            product_id: 0,
            products: "string",
          },
        ],
        products_favourite: [
          {
            products_favourite_id: 0,
            user_id: 0,
            users: {
              userId: 0,
              name: "string",
              mobile: "string",
              email: "string",
              otp: "string",
              password: "string",
              userPhoto: "string",
              role: "string",
              active: true,
              photo: "string",
              firstorder: true,
              is_client: true,
              passhash: "string",
              passhashsalt: "string",
              aspNetUserRoles: [
                {
                  id: 0,
                  role_Name: "string",
                  userId: 0,
                  users: "string",
                },
              ],
              categories: ["string"],
              productsFavourite: ["string"],
              shopping_cart: [
                {
                  shopping_cart_id: 0,
                  product_name: "string",
                  price: 0,
                  quantity: 0,
                  total_amount: 0,
                  status: "string",
                  created_at: "2025-04-18T07:44:26.517Z",
                  updated_at: "2025-04-18T07:44:26.517Z",
                  product_id: 0,
                  products: "string",
                  userId: 0,
                  users: "string",
                  order_id: 0,
                  orders: {
                    order_id: 0,
                    status: "string",
                    admin_id: 0,
                    user_id: 0,
                    total_amount: 0,
                    payment_id: 0,
                    created_at: "2025-04-18T07:44:26.517Z",
                    updated_at: "2025-04-18T07:44:26.517Z",
                    shopping_cart: ["string"],
                    notifications: ["string"],
                  },
                },
              ],
              rating: ["string"],
              notifications: [
                {
                  notifications_id: 0,
                  status: "string",
                  createdat: "2025-04-18T07:44:26.517Z",
                  userId: 0,
                  users: "string",
                  order_id: 0,
                  orders: {
                    order_id: 0,
                    status: "string",
                    admin_id: 0,
                    user_id: 0,
                    total_amount: 0,
                    payment_id: 0,
                    created_at: "2025-04-18T07:44:26.517Z",
                    updated_at: "2025-04-18T07:44:26.517Z",
                    shopping_cart: ["string"],
                    notifications: ["string"],
                  },
                },
              ],
            },
          },
        ],
      },
    ],
  },
];

export const allorders = [
  {
    order_id: 1,
    status: "قيد التنفيذ",
    total_amount: null,
    payment_id: 304563494,
    created_at: "2025-03-08T05:04:28.1132978",
    shopping_carddto: [
      {
        shopping_cart_id: 1,
        product_id: 2,
        product_name: "abaya1",
        price: 280,
        quantity: 1,
        total: 280,
        created_at: "2025-03-08T05:04:28.1654321",
        updated_at: "2025-03-08T05:04:28.165461",
      },
      {
        shopping_cart_id: 2,
        product_id: 4,
        product_name: "abaya3",
        price: 150,
        quantity: 1,
        total: 150,
        created_at: "2025-03-08T05:04:28.8469861",
        updated_at: "2025-03-08T05:04:28.8469899",
      },
      {
        shopping_cart_id: 3,
        product_id: 1,
        product_name: "abaya",
        price: 450,
        quantity: 1,
        total: 450,
        created_at: "2025-03-08T05:04:30.1418796",
        updated_at: "2025-03-08T05:04:30.1418831",
      },
      {
        shopping_cart_id: 4,
        product_id: 3,
        product_name: "abaya2",
        price: 450,
        quantity: 1,
        total: 450,
        created_at: "2025-03-08T05:04:30.8938699",
        updated_at: "2025-03-08T05:04:30.8938732",
      },
    ],
  },
  {
    order_id: 2,
    status: "قيد التنفيذ",
    total_amount: null,
    payment_id: 304564895,
    created_at: "2025-03-08T05:08:20.6477511",
    shopping_carddto: [
      {
        shopping_cart_id: 5,
        product_id: 4,
        product_name: "abaya3",
        price: 150,
        quantity: 1,
        total: 150,
        created_at: "2025-03-08T05:08:20.6591957",
        updated_at: "2025-03-08T05:08:20.6592009",
      },
      {
        shopping_cart_id: 6,
        product_id: 2,
        product_name: "abaya1",
        price: 280,
        quantity: 1,
        total: 280,
        created_at: "2025-03-08T05:08:20.9843105",
        updated_at: "2025-03-08T05:08:20.9843141",
      },
    ],
  },
  {
    order_id: 5,
    status: "قيد التنفيذ",
    total_amount: null,
    payment_id: 320054712,
    created_at: "2025-04-16T16:12:06.716251",
    shopping_carddto: [
      {
        shopping_cart_id: 10,
        product_id: 1,
        product_name: "abaya",
        price: 450,
        quantity: 2,
        total: 900,
        created_at: "2025-04-16T16:12:06.7338279",
        updated_at: "2025-04-16T16:13:58.6250201",
      },
      {
        shopping_cart_id: 11,
        product_id: 2,
        product_name: "abaya1",
        price: 280,
        quantity: 1,
        total: 280,
        created_at: "2025-04-16T16:12:16.8955806",
        updated_at: "2025-04-16T16:12:16.8955871",
      },
      {
        shopping_cart_id: 12,
        product_id: 4,
        product_name: "abaya3",
        price: 150,
        quantity: 1,
        total: 150,
        created_at: "2025-04-16T16:14:08.1815298",
        updated_at: "2025-04-16T16:14:08.1815359",
      },
      {
        shopping_cart_id: 13,
        product_id: 3,
        product_name: "abaya2",
        price: 450,
        quantity: 1,
        total: 450,
        created_at: "2025-04-16T16:34:10.8629764",
        updated_at: "2025-04-16T16:34:10.8629817",
      },
    ],
  },
];

export const allclients = [
  {
    userId: 1,
    name: "client 1",
    mobile: "+201026682015",
    email: "client 1@gmail.com",
    otp: "1111",
    userPhoto: "string",
    active: true,
  },
  {
    userId: 2,
    name: "client 2",
    mobile: "+201026682015",
    email: "client 1@gmail.com",
    otp: "1111",
    userPhoto: "client.png",
    active: true,
  },
  {
    userId: 3,
    name: "client 3",
    mobile: "+201026682015",
    email: "client 1@gmail.com",
    otp: "1111",
    userPhoto: "string",
    active: true,
  },
];
